name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Frontend Tests
    - name: Install Frontend Dependencies
      working-directory: ./
      run: npm install

    - name: Run Frontend Tests (Vitest)
      working-directory: ./
      run: npm run test

    # Backend Tests
    - name: Install Backend Dependencies
      working-directory: ./back-end
      run: npm install

    - name: Run Backend Tests (Jest)
      working-directory: ./back-end
      run: npm run test
